
name: "lego"
render_settings:
  model_path: "./output/lego@20240322-205727/results/point_cloud/iteration_30000/point_cloud.ply"
  save_path: "./output/render"
  render_modes: ['rgb']

repr: 
  max_sh_degree: 3

renderer:
  background_color: [0,0,0]
  compute_cov3D_python: False
  convert_SHs_python: False
  scaling_modifier: 1.0
  prefiltered: False
  override_color: [-1,-1,-1]
  debug: False

data:
  source_path: "D:/data/lego/"
  eval: 0
  shuffle: True
  resolution: -1
  resolution_scales: [1.0]

logger:
  version: 1
  disable_existing_loggers: False
  formatters:
    datetime:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    simple:
      format: "%(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      formatter: "simple"
      level: "VERBOSE"
      stream: "ext://sys.stdout"
    info_file_handler:
      backupCount: 20
      class: "logging.handlers.RotatingFileHandler"
      encoding: "utf8"
      filename: "info.log"
      formatter: "datetime"
      level: "INFO"
      maxBytes: 10485760
  root:
    handlers:
    - "console"
    - "info_file_handler"
    level: "VERBOSE"